---
title: "Stratégies et secteurs de croissances pour les sociétés d'ingénierie : Numérique 2"
author: "ENZI"
date: "11/04/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment=NA)
```

## Introduction

```{r Packages, message=FALSE}
library(tidyverse)
library(tidytext)
```

```{r getting data}
csv_data <- read_csv("csv-thesaurus-matching/test_filter_Quelles_stratégies_et_secteurs_de_croissance_pour_les_sociétés_d_ingénierie_Numérique_2_20170412-114612.csv")
csv_data
```

```{r data processing}
clean_csv_data <- mutate(csv_data, interest_lvl = as.factor(interest_lvl), nb_list_matched = as.factor(list_1 + list_2 + list_3), total_lists = 3, list_1 = as.logical(list_1), list_2 = as.logical(list_2), list_3 = as.logical(list_3))
clean_csv_data
```

```{r summary data}
filtered_data <- select(clean_csv_data, hash, interest_lvl, nb_list_matched)
filtered_data %>%
  ggplot(aes(x = interest_lvl, y = nb_list_matched, fill = interest_lvl)) + geom_col()
```

```{r}
splitted_queries <- strsplit(queries$search, split = sepa) %>%
  map(~gsub(.x, pattern = '\"',replacement = ''))

searches_terms <- tibble(
                          thesaurus1 = character(nrow(queries)),
                          thesaurus2 = character(nrow(queries)),
                          thesaurus3 = character(nrow(queries))
                         )

searches_terms$thesaurus1 <- map_chr(splitted_queries, ~ paste(" ", .x[[1]], " "))

searches_terms$thesaurus2 <- map_chr(splitted_queries, ~ paste(" ", .x[[2]], " "))

searches_terms$thesaurus3 <- map_chr(splitted_queries, ~ paste(" ", .x[[3]], " "))

#searches_terms <- tibble(
 #                         thesaurus1 = character(nrow(queries)),
 #                         thesaurus2 = character(nrow(queries)),
  #                        thesaurus3 = character(nrow(queries))
   #                      )
#assign(searches_terms$thesaurus1, map_chr(splitted_queries, ~ paste(" ", .x[[1]] %>%
#                                          gsub(pattern = '\"',replacement = ''), 
#                                        " ")
#)
#)
#test <- map(searches_terms, ~ assign(.x, value = map_chr(splitted_queries, paste(" ", .x[[1]] %>%
#                                                                                   gsub(pattern = '\"',replacement = ''),
#                                                                                 " "
 #                                                                                )
   #                                                      )
  #                                   )
      #      )

#test <- map(searches_terms, ~ .x) %>% assign(value = map_chr(splitted_queries, paste(" ", .x[[1]] %>%
         #                                                                          gsub(pattern = '\"',replacement = ''),
           #                                                                      " "
             #                                                                    )
                 #                                        )
                    #                 )
#searches_terms
#splitted_queries
searches_terms
```

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
